install.packages("twitteR")
install.packages("httr")
install.packages("SnowballC")
install.packages("tm")
install.packages("RColorBrewer")
install.packages("wordcloud")
install.packages("stringr")
install.packages("plyr")
install.packages("lattice")
install.packages("Rstem")
install.packages("sentiment")

library("twitteR")
library("httr")
library("SnowballC")
library("tm")
library("RColorBrewer")
library("wordcloud")
library("stringr")
library("plyr")
library("lattice")
library("Rstem")
library("sentiment")
library("ggplot2")

setup_twitter_oauth(consumer, consumer_secret, access_token, access_secret)
tweets<-searchTwitter("vacina", n = 7000, lang = "pt")

data <- twListToDF(tweets)
situation <- Corpus(VectorSource(data$text)) 
situation <- tm_map(situation, tolower)
situation <- tm_map(situation, removePunctuation)
situation <- tm_map(situation, stripWhitespace)
situation <- tm_map(situation, removeNumbers)
situation <- tm_map(situation, removeWords, stopwords(kind= "pt"))
control <- as.matrix(TermDocumentMatrix(situation, control = list(stemming = TRUE)))
c <- rowSums(control)
c <- sort(c, decreasing = TRUE)
head(c)
wordcloud(situation, min.freq = 40, max.words = 40, random.order = FALSE, rot.per = 0.35, colors = brewer.pal(8,"Dark2"))

                                                                            
